{{- if not .Values.externalSecrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lons.secretName" . }}
  labels:
    {{- include "lons.labels" . | nindent 4 }}
  annotations:
    external-secrets.io/managed: "false"
type: Opaque
data:
  DATABASE_URL: ""
  REDIS_URL: ""
  JWT_PRIVATE_KEY: ""
  JWT_PUBLIC_KEY: ""
  ENCRYPTION_KEY: ""
  VAULT_TOKEN: ""
{{- end }}
