{{- if .Values.graphqlServer.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "lons.fullname" . }}-graphql-server
  labels:
    {{- include "lons.componentLabels" (dict "context" . "component" "graphql-server") | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "lons.fullname" . }}-graphql-server
  minReplicas: {{ .Values.graphqlServer.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.graphqlServer.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.graphqlServer.autoscaling.targetCPUUtilizationPercentage }}
{{- end }}
