{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: {{ include "lons.fullname" . }}-aws-sm
  labels:
    {{- include "lons.labels" . | nindent 4 }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.externalSecrets.aws.region }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ .Values.externalSecrets.serviceAccount.name | default "external-secrets-sa" }}
            namespace: {{ .Values.externalSecrets.serviceAccount.namespace | default "external-secrets" }}
{{- end }}
