{{- if .Values.tracing.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "lons.fullname" . }}-otel-collector
  labels:
    {{- include "lons.componentLabels" (dict "context" . "component" "otel-collector") | nindent 4 }}
{{- end }}
