# EKS Module Outputs

output "cluster_endpoint" {
  description = "Endpoint for EKS control plane"
  value       = aws_eks_cluster.main.endpoint
}

output "cluster_name" {
  description = "Name of the EKS cluster"
  value       = aws_eks_cluster.main.name
}

output "cluster_version" {
  description = "Kubernetes version for the EKS cluster"
  value       = aws_eks_cluster.main.version
}

output "cluster_arn" {
  description = "ARN of the EKS cluster"
  value       = aws_eks_cluster.main.arn
}

output "cluster_certificate_authority" {
  description = "Base64 encoded certificate data required to communicate with the cluster"
  value       = aws_eks_cluster.main.certificate_authority[0].data
  sensitive   = true
}

output "cluster_security_group_id" {
  description = "Security group ID attached to the EKS cluster"
  value       = aws_eks_cluster.main.vpc_config[0].cluster_security_group_id
}

output "cluster_iam_role_arn" {
  description = "IAM role ARN of the EKS cluster"
  value       = aws_iam_role.cluster.arn
}

output "node_group_id" {
  description = "EKS node group ID"
  value       = aws_eks_node_group.main.id
}

output "node_group_role_arn" {
  description = "IAM role ARN of the EKS node group"
  value       = aws_iam_role.node_group.arn
}

output "node_group_role_name" {
  description = "IAM role name of the EKS node group"
  value       = aws_iam_role.node_group.name
}

output "oidc_provider_arn" {
  description = "ARN of the OIDC provider for IRSA (IAM Roles for Service Accounts)"
  value       = aws_iam_openid_connect_provider.eks.arn
}

output "oidc_provider_url" {
  description = "URL of the OIDC provider for IRSA"
  value       = aws_iam_openid_connect_provider.eks.url
}

output "oidc_provider_arn_short" {
  description = "OIDC provider identifier (without https://)"
  value       = replace(aws_iam_openid_connect_provider.eks.url, "https://", "")
}

output "aws_load_balancer_controller_role_arn" {
  description = "IAM role ARN for the AWS Load Balancer Controller service account"
  value       = aws_iam_role.aws_load_balancer_controller.arn
}

output "ebs_csi_driver_role_arn" {
  description = "IAM role ARN for the EBS CSI Driver service account"
  value       = aws_iam_role.ebs_csi_driver.arn
}

output "cluster_log_group_name" {
  description = "CloudWatch log group name for EKS cluster logs"
  value       = var.enable_logging ? aws_cloudwatch_log_group.eks_cluster[0].name : ""
}

output "kms_key_arn" {
  description = "ARN of the KMS key used for EKS cluster encryption (only if created by module)"
  value       = var.kms_key_id != "" ? var.kms_key_id : aws_kms_key.eks[0].arn
}

output "kms_key_id" {
  description = "ID of the KMS key used for EKS cluster encryption"
  value       = var.kms_key_id != "" ? var.kms_key_id : aws_kms_key.eks[0].id
}

output "vpc_config" {
  description = "VPC configuration for the EKS cluster"
  value = {
    subnet_ids              = aws_eks_cluster.main.vpc_config[0].subnet_ids
    vpc_id                  = aws_eks_cluster.main.vpc_config[0].vpc_id
    security_group_ids      = aws_eks_cluster.main.vpc_config[0].security_group_ids
    cluster_security_group_id = aws_eks_cluster.main.vpc_config[0].cluster_security_group_id
  }
}

output "addon_versions" {
  description = "Versions of installed EKS addons"
  value = {
    vpc_cni          = aws_eks_addon.vpc_cni.addon_version
    coredns          = aws_eks_addon.coredns.addon_version
    kube_proxy       = aws_eks_addon.kube_proxy.addon_version
    ebs_csi_driver   = aws_eks_addon.ebs_csi_driver.addon_version
  }
}

output "kubeconfig" {
  description = "kubectl config as generated by the module (base64 encoded)"
  value = base64encode(yamlencode({
    apiVersion      = "v1"
    kind            = "Config"
    current-context = "${var.project_name}/${var.environment}"
    clusters = [
      {
        name = aws_eks_cluster.main.id
        cluster = {
          server                   = aws_eks_cluster.main.endpoint
          certificate-authority-data = aws_eks_cluster.main.certificate_authority[0].data
        }
      }
    ]
    contexts = [
      {
        name = "${var.project_name}/${var.environment}"
        context = {
          cluster = aws_eks_cluster.main.id
          user    = aws_eks_cluster.main.id
        }
      }
    ]
    users = [
      {
        name = aws_eks_cluster.main.id
        user = {
          exec = {
            apiVersion = "client.authentication.k8s.io/v1beta1"
            command    = "aws"
            args       = ["eks", "get-token", "--cluster-name", aws_eks_cluster.main.id]
          }
        }
      }
    ]
  }))
  sensitive = true
}
