export const DEFAULTS = {
  JWT_EXPIRY_SECONDS: 3600,
  REFRESH_TOKEN_EXPIRY_SECONDS: 604800,
  MAX_FAILED_LOGIN_ATTEMPTS: 5,
  LOCKOUT_DURATION_MINUTES: 15,
  SESSION_TIMEOUT_MINUTES: 30,
  PAGINATION_DEFAULT_LIMIT: 20,
  PAGINATION_MAX_LIMIT: 100,
  IDEMPOTENCY_KEY_TTL_HOURS: 24,
  GRAPHQL_MAX_COMPLEXITY: 1000,
  GRAPHQL_MAX_DEPTH: 7,
  PASSWORD_MIN_LENGTH: 12,
  BCRYPT_ROUNDS: 12,
} as const;
