import { Injectable, Logger } from '@nestjs/common';
import { Cron, CronExpression } from '@nestjs/schedule';
import { PrismaService } from '@lons/database';

/**
 * Strict identifier guard for audit-log partition names. Partition names are
 * machine-generated by `formatPartitionName(year, month)` so they always match
 * `audit_logs_YYYY_MM`, but we still validate before splicing into DDL —
 * Postgres can't parameterize identifiers, so we have to be defensive.
 */
const PARTITION_NAME_RE = /^audit_logs_\d{4}_\d{2}$/;
const ISO_DATE_RE = /^\d{4}-\d{2}-\d{2}$/;

@Injectable()
export class AuditPartitionManager {
  private readonly logger = new Logger(AuditPartitionManager.name);
  private readonly retentionMonths: number;

  constructor(private readonly prisma: PrismaService) {
    this.retentionMonths = parseInt(process.env.AUDIT_LOG_RETENTION_MONTHS || '24', 10);
  }

  @Cron(CronExpression.EVERY_1ST_DAY_OF_MONTH_AT_MIDNIGHT)
  async managePartitions(): Promise<void> {
    this.logger.log('Running audit log partition management');
    // Sprint 10B Task 0: DDL on the audit_logs partition tree runs at the
    // platform tier. Wrap in admin context so RLS / pg_catalog queries
    // aren't restricted to a single tenant.
    await this.prisma.enterTenantContext({ isPlatformAdmin: true }, async () => {
      await this.createFuturePartitions();
      await this.dropExpiredPartitions();
    });
  }

  private formatPartitionName(date: Date): string {
    return `audit_logs_${date.getFullYear()}_${String(date.getMonth() + 1).padStart(2, '0')}`;
  }

  private async createFuturePartitions(): Promise<void> {
    const now = new Date();
    for (let i = 1; i <= 3; i++) {
      const date = new Date(now.getFullYear(), now.getMonth() + i, 1);
      const nextMonth = new Date(date.getFullYear(), date.getMonth() + 1, 1);
      const partitionName = this.formatPartitionName(date);
      const fromDate = date.toISOString().split('T')[0];
      const toDate = nextMonth.toISOString().split('T')[0];

      // Defense in depth: every value spliced into the DDL is shape-validated.
      // Postgres doesn't allow parameter binding for identifiers or for the
      // FROM/TO partition bounds, so $executeRawUnsafe is unavoidable here.
      if (!PARTITION_NAME_RE.test(partitionName) || !ISO_DATE_RE.test(fromDate) || !ISO_DATE_RE.test(toDate)) {
        this.logger.error(
          `Refusing to create partition with malformed name or bounds: ${partitionName}`,
        );
        continue;
      }

      try {
        await this.prisma.$executeRawUnsafe(
          `CREATE TABLE IF NOT EXISTS ${partitionName} PARTITION OF audit_logs FOR VALUES FROM ('${fromDate}') TO ('${toDate}')`,
        );
        this.logger.log(`Ensured partition ${partitionName} exists`);
      } catch (error: any) {
        if (!error.message?.includes('already exists')) {
          this.logger.error(`Failed to create partition ${partitionName}`, error);
        }
      }
    }
  }

  private async dropExpiredPartitions(): Promise<void> {
    const cutoff = new Date();
    cutoff.setMonth(cutoff.getMonth() - this.retentionMonths);
    const cutoffName = this.formatPartitionName(cutoff);

    const partitions = await this.prisma.$queryRaw<{ tablename: string }[]>`
      SELECT tablename FROM pg_tables
      WHERE tablename LIKE 'audit_logs_%'
      AND tablename < ${cutoffName}
      AND schemaname = 'public'
    `;

    for (const partition of partitions) {
      // tablename comes from pg_tables (database-controlled), not user input,
      // but validate anyway — defense in depth costs nothing.
      if (!PARTITION_NAME_RE.test(partition.tablename)) {
        this.logger.error(
          `Refusing to drop partition with unexpected name: ${partition.tablename}`,
        );
        continue;
      }
      try {
        await this.prisma.$executeRawUnsafe(`DROP TABLE IF EXISTS ${partition.tablename}`);
        this.logger.log(`Dropped expired partition ${partition.tablename}`);
      } catch (error) {
        this.logger.error(`Failed to drop partition ${partition.tablename}`, error);
      }
    }
  }
}
